# evaluate-simplified-rules.R
#
# This script evaluates the accuracy of simplified prose rules against
# the original training data. It compares:
# 1. Original decision tree predictions
# 2. Simplified rule predictions
# 3. Actual crop tree status
#
# Usage:
#   source("R/evaluate-simplified-rules.R")
#   # Results will print to console and save to output directory

library(dplyr)
library(rpart)

# =============================================================================
# STEP 1: Load the training data
# =============================================================================
#
# NOTE: You must first save the training data by adding this line to run.R
# after crops_all is created (around line 129):
#   saveRDS(crops_all, "output/decision-trees/dataset2/crops_all.rds")
#
# Then re-run run.R, or just run these lines in R after sourcing the setup:
#   source("R/data2.R"); source("R/simulation.R"); source("R/lev.R"); source("R/fct-croptrees.R")
#   crops_all <- crop_trees(sim$trees, .02, 1, levs = lev_lookup)
#   for (dr in c(.03, .04, .05, .06)) crops_all <- rbind(crops_all, crop_trees(sim$trees, dr, 1, levs = lev_lookup))
#   saveRDS(crops_all, "output/decision-trees/dataset2/crops_all.rds")

message("=== Loading training data ===\n")

crops_file <- "output/decision-trees/dataset2/crops_all.rds"

if (!file.exists(crops_file)) {
  stop("Training data not found at: ", crops_file, "\n",
       "Please save crops_all first. See comments in this script for instructions.")
}

crops_all <- readRDS(crops_file)

message("Training data: ", nrow(crops_all), " observations")
message("Species: ", paste(unique(crops_all$spp), collapse = ", "))
message("Sites: ", paste(unique(crops_all$site), collapse = ", "))
message("Discount rates: ", paste(unique(crops_all$drate), collapse = ", "))

# =============================================================================
# STEP 2: Define simplified rules as functions
# =============================================================================

# These rules are derived from the prose summaries generated by
# summarize-decision-trees.R. Each function returns TRUE if crop tree.

simplified_rules <- list(

  # BM: DBH <= 13" for any grade, or <= 14" if veneer; CR >= 35%
  # Discount rate: -0.8" per 1% increase from 3%
  # Site: granitictill -0.8"
  BM = function(dbh, cr, best_log, site, drate) {
    # Base thresholds at 3%
    base_dbh_any <- 13
    base_dbh_veneer <- 14
    base_cr <- 35

    # Adjust for discount rate (base is 3%)
    drate_adj <- -0.8 * (drate * 100 - 3)

    # Adjust for site
    site_adj <- case_when(
      site == "granitictill" ~ -0.8,
      TRUE ~ 0
    )

    # Apply adjustments
    max_dbh_any <- base_dbh_any + drate_adj + site_adj
    max_dbh_veneer <- base_dbh_veneer + drate_adj + site_adj

    # Rule: crop if CR >= 35% AND (DBH <= max_any OR (veneer AND DBH <= max_veneer))
    cr >= base_cr & (dbh <= max_dbh_any | (best_log == 1 & dbh <= max_dbh_veneer))
  },

  # PB: Veneer only, DBH <= 16", CR >= 45%
  # Discount rate: -0.7" per 1% increase from 3%
  # Site: mountaintill +1.2", clayplain -0.8", richnhw -0.8"
  PB = function(dbh, cr, best_log, site, drate) {
    base_dbh <- 16
    base_cr <- 45

    drate_adj <- -0.7 * (drate * 100 - 3)

    site_adj <- case_when(
      site == "mountaintill" ~ 1.2,
      site == "clayplain" ~ -0.8,
      site == "richnhw" ~ -0.8,
      TRUE ~ 0
    )

    max_dbh <- base_dbh + drate_adj + site_adj

    # Rule: crop only if veneer AND CR >= 45% AND DBH <= max
    best_log == 1 & cr >= base_cr & dbh <= max_dbh
  },

  # RM: Veneer <= 17", Sawlog <= 14", CR >= 25%
  # Discount rate: -1" per 1% increase from 3%
  # Site: granitictill +0.8", mountaintill +0.8", clayplain -1.2"
  RM = function(dbh, cr, best_log, site, drate) {
    base_dbh_veneer <- 17
    base_dbh_sawlog <- 14
    base_cr <- 25

    drate_adj <- -1.0 * (drate * 100 - 3)

    site_adj <- case_when(
      site == "granitictill" ~ 0.8,
      site == "mountaintill" ~ 0.8,
      site == "clayplain" ~ -1.2,
      TRUE ~ 0
    )

    max_dbh_veneer <- base_dbh_veneer + drate_adj + site_adj
    max_dbh_sawlog <- base_dbh_sawlog + drate_adj + site_adj

    # Rule: crop if CR >= 25% AND DBH within grade-specific limit
    cr >= base_cr & ((best_log == 1 & dbh <= max_dbh_veneer) |
                      (best_log == 2 & dbh <= max_dbh_sawlog))
  },

  # SO: CR >= 35%: DBH <= 18"; CR < 35%: DBH <= 13"; Veneer bonus +4"
  # Discount rate: -1.1" per 1% increase from 3%
  # Site: mountaintill +2.2", granitictill -0.8", clayplain -1.8"
  SO = function(dbh, cr, best_log, site, drate) {
    base_dbh_high_cr <- 18
    base_dbh_low_cr <- 13
    cr_threshold <- 35
    veneer_bonus <- 4

    drate_adj <- -1.1 * (drate * 100 - 3)

    site_adj <- case_when(
      site == "mountaintill" ~ 2.2,
      site == "granitictill" ~ -0.8,
      site == "clayplain" ~ -1.8,
      TRUE ~ 0
    )

    # Determine base DBH limit based on CR
    base_dbh <- ifelse(cr >= cr_threshold, base_dbh_high_cr, base_dbh_low_cr)

    # Add veneer bonus if applicable
    grade_bonus <- ifelse(best_log == 1, veneer_bonus, 0)

    max_dbh <- base_dbh + drate_adj + site_adj + grade_bonus

    # Rule: crop if DBH <= adjusted max (no minimum CR since CR determines the base)
    dbh <= max_dbh
  },

  # WO: CR >= 35%: DBH <= 19"; CR < 35%: DBH <= 13"; Veneer bonus +5"
  # Discount rate: -1.4" per 1% increase from 3%
  # Site: mountaintill +1.8", clayplain -1.2"
  WO = function(dbh, cr, best_log, site, drate) {
    base_dbh_high_cr <- 19
    base_dbh_low_cr <- 13
    cr_threshold <- 35
    veneer_bonus <- 5

    drate_adj <- -1.4 * (drate * 100 - 3)

    site_adj <- case_when(
      site == "mountaintill" ~ 1.8,
      site == "clayplain" ~ -1.2,
      TRUE ~ 0
    )

    base_dbh <- ifelse(cr >= cr_threshold, base_dbh_high_cr, base_dbh_low_cr)
    grade_bonus <- ifelse(best_log == 1, veneer_bonus, 0)

    max_dbh <- base_dbh + drate_adj + site_adj + grade_bonus

    dbh <= max_dbh
  },

  # YB: CR >= 30%: DBH <= 21"; CR < 30%: DBH <= 17"
  # Discount rate: -1.6" per 1% increase from 3%
  # Site: richnhw +1.5", granitictill -1.5"
  YB = function(dbh, cr, best_log, site, drate) {
    base_dbh_high_cr <- 21
    base_dbh_low_cr <- 17
    cr_threshold <- 30

    drate_adj <- -1.6 * (drate * 100 - 3)

    site_adj <- case_when(
      site == "richnhw" ~ 1.5,
      site == "granitictill" ~ -1.5,
      TRUE ~ 0
    )

    base_dbh <- ifelse(cr >= cr_threshold, base_dbh_high_cr, base_dbh_low_cr)
    max_dbh <- base_dbh + drate_adj + site_adj

    dbh <= max_dbh
  },

  # WP: Never a crop tree
  WP = function(dbh, cr, best_log, site, drate) {
    rep(FALSE, length(dbh))
  }
)


# =============================================================================
# STEP 3: Apply simplified rules and calculate accuracy
# =============================================================================

message("\n=== Applying simplified rules ===\n")

# Apply simplified rules to each observation
crops_all$simplified_pred <- NA

for (spp_code in names(simplified_rules)) {
  idx <- crops_all$spp == spp_code
  if (sum(idx) > 0) {
    rule_fn <- simplified_rules[[spp_code]]
    crops_all$simplified_pred[idx] <- rule_fn(
      crops_all$dbh[idx],
      crops_all$cr[idx],
      crops_all$best_log[idx],
      crops_all$site[idx],
      crops_all$drate[idx]
    )
  }
}

# Also get original tree predictions for comparison
message("Loading original decision trees for comparison...")

tree_dir <- "output/decision-trees/dataset2"
crops_all$tree_pred <- NA

for (i in 1:nrow(crops_all)) {
  spp <- crops_all$spp[i]
  site <- crops_all$site[i]
  drate <- crops_all$drate[i]

  # Construct filename
  fname <- sprintf("dt_%s_%s_%dpct.rds", spp, site, round(drate * 100))
  fpath <- file.path(tree_dir, fname)

  if (file.exists(fpath)) {
    tree <- readRDS(fpath)
    if (inherits(tree, "rpart")) {
      # Get prediction for this observation
      pred <- predict(tree, crops_all[i, ], type = "class")
      crops_all$tree_pred[i] <- as.character(pred) == "TRUE"
    } else if (is.list(tree) && "note" %in% names(tree)) {
      # Handle edge cases
      if (grepl("No crop", tree$note)) {
        crops_all$tree_pred[i] <- FALSE
      } else if (grepl("All trees are crop", tree$note)) {
        crops_all$tree_pred[i] <- TRUE
      }
    }
  }
}

# =============================================================================
# STEP 4: Calculate accuracy metrics
# =============================================================================

message("\n=== Calculating accuracy metrics ===\n")

# Function to calculate metrics from confusion matrix
calc_metrics <- function(actual, predicted) {
  # Handle NA
  valid <- !is.na(actual) & !is.na(predicted)
  actual <- actual[valid]
  predicted <- predicted[valid]

  if (length(actual) == 0) {
    return(c(n = 0, accuracy = NA, precision = NA, recall = NA,
             specificity = NA, f1 = NA, fpr = NA, fnr = NA))
  }

  tp <- sum(predicted & actual)
  fp <- sum(predicted & !actual)
  tn <- sum(!predicted & !actual)
  fn <- sum(!predicted & actual)
  n <- tp + fp + tn + fn

  accuracy <- (tp + tn) / n
  precision <- ifelse(tp + fp > 0, tp / (tp + fp), NA)
  recall <- ifelse(tp + fn > 0, tp / (tp + fn), NA)
  specificity <- ifelse(tn + fp > 0, tn / (tn + fp), NA)
  f1 <- ifelse(!is.na(precision) & !is.na(recall) & (precision + recall) > 0,
               2 * precision * recall / (precision + recall), NA)
  fpr <- ifelse(fp + tn > 0, fp / (fp + tn), NA)
  fnr <- ifelse(fn + tp > 0, fn / (fn + tp), NA)

  c(n = n, accuracy = accuracy, precision = precision, recall = recall,
    specificity = specificity, f1 = f1, fpr = fpr, fnr = fnr)
}

# Calculate metrics by species
results_by_species <- crops_all %>%
  filter(spp != "WP") %>%  # Exclude WP
  group_by(spp) %>%
  summarise(
    n = n(),
    # Simplified rule metrics
    simp_accuracy = calc_metrics(crop, simplified_pred)["accuracy"],
    simp_precision = calc_metrics(crop, simplified_pred)["precision"],
    simp_recall = calc_metrics(crop, simplified_pred)["recall"],
    simp_f1 = calc_metrics(crop, simplified_pred)["f1"],
    simp_fpr = calc_metrics(crop, simplified_pred)["fpr"],
    simp_fnr = calc_metrics(crop, simplified_pred)["fnr"],
    # Original tree metrics
    tree_accuracy = calc_metrics(crop, tree_pred)["accuracy"],
    tree_precision = calc_metrics(crop, tree_pred)["precision"],
    tree_recall = calc_metrics(crop, tree_pred)["recall"],
    tree_f1 = calc_metrics(crop, tree_pred)["f1"],
    tree_fpr = calc_metrics(crop, tree_pred)["fpr"],
    tree_fnr = calc_metrics(crop, tree_pred)["fnr"],
    # Agreement between simplified and tree
    agreement = mean(simplified_pred == tree_pred, na.rm = TRUE),
    .groups = "drop"
  )

# Print results
message("\n", paste(rep("=", 70), collapse = ""))
message("SIMPLIFIED RULE ACCURACY BY SPECIES")
message(paste(rep("=", 70), collapse = ""), "\n")

cat("\n--- Simplified Rule Performance ---\n")
print(results_by_species %>%
        select(spp, n, simp_accuracy, simp_precision, simp_recall, simp_f1, simp_fpr, simp_fnr) %>%
        mutate(across(where(is.numeric) & !n, ~round(., 3))))

cat("\n--- Original Decision Tree Performance ---\n")
print(results_by_species %>%
        select(spp, n, tree_accuracy, tree_precision, tree_recall, tree_f1, tree_fpr, tree_fnr) %>%
        mutate(across(where(is.numeric) & !n, ~round(., 3))))

cat("\n--- Comparison (Simplified vs Original Tree) ---\n")
comparison <- results_by_species %>%
  select(spp, n, agreement,
         simp_accuracy, tree_accuracy,
         simp_f1, tree_f1) %>%
  mutate(
    accuracy_diff = simp_accuracy - tree_accuracy,
    f1_diff = simp_f1 - tree_f1
  ) %>%
  mutate(across(where(is.numeric) & !n, ~round(., 3)))
print(comparison)

# Calculate overall metrics
message("\n--- Overall Summary ---\n")
overall_simp <- calc_metrics(crops_all$crop[crops_all$spp != "WP"],
                              crops_all$simplified_pred[crops_all$spp != "WP"])
overall_tree <- calc_metrics(crops_all$crop[crops_all$spp != "WP"],
                              crops_all$tree_pred[crops_all$spp != "WP"])

cat("Simplified Rules (all species):\n")
cat(sprintf("  Accuracy: %.1f%%\n", overall_simp["accuracy"] * 100))
cat(sprintf("  Precision: %.1f%%\n", overall_simp["precision"] * 100))
cat(sprintf("  Recall: %.1f%%\n", overall_simp["recall"] * 100))
cat(sprintf("  F1 Score: %.3f\n", overall_simp["f1"]))
cat(sprintf("  False Positive Rate: %.1f%%\n", overall_simp["fpr"] * 100))
cat(sprintf("  False Negative Rate: %.1f%%\n", overall_simp["fnr"] * 100))

cat("\nOriginal Decision Trees (all species):\n")
cat(sprintf("  Accuracy: %.1f%%\n", overall_tree["accuracy"] * 100))
cat(sprintf("  Precision: %.1f%%\n", overall_tree["precision"] * 100))
cat(sprintf("  Recall: %.1f%%\n", overall_tree["recall"] * 100))
cat(sprintf("  F1 Score: %.3f\n", overall_tree["f1"]))
cat(sprintf("  False Positive Rate: %.1f%%\n", overall_tree["fpr"] * 100))
cat(sprintf("  False Negative Rate: %.1f%%\n", overall_tree["fnr"] * 100))

# Save results
output_file <- file.path(tree_dir, "simplified_rule_accuracy.csv")
write.csv(results_by_species, output_file, row.names = FALSE)
message("\nResults saved to: ", output_file)

# =============================================================================
# STEP 5: Detailed breakdown by species/site/drate
# =============================================================================

message("\n", paste(rep("=", 70), collapse = ""))
message("DETAILED BREAKDOWN BY SPECIES")
message(paste(rep("=", 70), collapse = ""), "\n")

for (spp_code in unique(crops_all$spp[crops_all$spp != "WP"])) {
  cat("\n### ", spp_code, " ###\n")

  spp_data <- crops_all %>% filter(spp == spp_code)

  # By site
  by_site <- spp_data %>%
    group_by(site) %>%
    summarise(
      n = n(),
      simp_acc = mean(simplified_pred == crop, na.rm = TRUE),
      tree_acc = mean(tree_pred == crop, na.rm = TRUE),
      .groups = "drop"
    ) %>%
    mutate(across(where(is.numeric) & !n, ~round(., 3)))

  cat("\nBy Site:\n")
  print(by_site)

  # By discount rate
  by_drate <- spp_data %>%
    group_by(drate) %>%
    summarise(
      n = n(),
      simp_acc = mean(simplified_pred == crop, na.rm = TRUE),
      tree_acc = mean(tree_pred == crop, na.rm = TRUE),
      .groups = "drop"
    ) %>%
    mutate(across(where(is.numeric) & !n, ~round(., 3)))

  cat("\nBy Discount Rate:\n")
  print(by_drate)
}
